@startuml

class DockingStation {
capacity
broken_bikes
accept(bikes)
release(num_bikes)
ship(num_bikes)
}

class Garage {
bikes_to_fix
fixed_bikes
accept(bikes)
fix_bikes(num = 1)
ship(num_bikes)
}

class Van {
transported_bikes
retrieve(num_bikes, source)
deliver(num_bikes, destination)
}

class Bike {
report_broken()
fix()
working?()
broken?()
}

@enduml